export const termsOfUseContent = `
# Terms of Use

**Last Updated:** 13 January 2026

**Effective Date:** 13 January 2026


Welcome to **PlanProject.ai** (“Platform”, “Service”, “we”, “us”, “our”). These Terms of Use (“Terms”) govern your access to and use of https://planproject.ai/ and any related services, features, or content.

By accessing or using the Platform, you agree to be bound by these Terms. If you do not agree, do not use the Platform.

---

## 1. Use of the Service

PlanProject.ai is provided for general informational, planning, and productivity purposes only. You agree to use the Platform solely at your own risk and in compliance with all applicable laws.

You are responsible for:
- Any actions taken based on outputs, suggestions, or results generated by the Platform  
- Verifying the accuracy, completeness, and suitability of any information before relying on it  
- How you use, interpret, or apply the Service in real-world scenarios  

---

## 2. Service Provided “AS IS” and “AS AVAILABLE”

**The Platform is provided strictly on an “AS IS” and “AS AVAILABLE” basis.**

To the fullest extent permitted by law:
- We make **no warranties**, express or implied  
- We do **not guarantee accuracy, reliability, availability, or fitness for any purpose**  
- We do **not guarantee uninterrupted or error-free operation**  

You acknowledge that the Service may contain bugs, errors, limitations, or inaccuracies.

---

## 3. No Responsibility or Liability

**The owner, developer, operators, and contributors of PlanProject.ai assume NO responsibility or liability for any issues, damages, losses, or consequences arising from:**
- Use or inability to use the Platform  
- Reliance on any output, recommendation, or result generated by the Platform  
- Decisions, actions, or omissions taken by any user or third party  
- Data loss, business interruption, financial loss, reputational harm, or indirect damages  

This applies **regardless of cause**, including but not limited to negligence, system errors, or third-party failures.

---

## 4. AI-Generated Content Disclaimer

The Platform may use artificial intelligence and automated systems to generate content or suggestions. You understand and agree that:
- AI-generated outputs may be incorrect, incomplete, outdated, or misleading  
- Outputs are **not professional advice** (legal, financial, medical, or otherwise)  
- You must independently verify all information before use  

PlanProject.ai is **not responsible for how AI-generated content is used or interpreted**.

---

## 5. Limitation of Liability

To the maximum extent permitted by applicable law:
- We shall **not be liable for any direct, indirect, incidental, special, consequential, or punitive damages**
- Our total liability, if any, shall not exceed the amount you paid to use the Service (if applicable), or zero where the Service is free

Some jurisdictions do not allow certain liability limitations; in such cases, liability is limited to the minimum extent required by law.

---

## 6. User Responsibility and Indemnification

You agree to indemnify and hold harmless PlanProject.ai, its owner, developer, and affiliates from any claims, damages, losses, liabilities, or expenses arising from:
- Your use of the Platform  
- Your violation of these Terms  
- Your reliance on Platform outputs  
- Any content or data you provide  

---

## 7. Availability and Modifications

We reserve the right to:
- Modify, suspend, or discontinue the Platform at any time  
- Change features, functionality, or access without notice  
- Update these Terms at our discretion  

Continued use of the Platform after changes constitutes acceptance of the updated Terms.

---

## 8. Intellectual Property

All content, branding, software, and intellectual property related to PlanProject.ai remain the exclusive property of the Platform owner unless otherwise stated.

You may not copy, modify, distribute, reverse engineer, or exploit any part of the Platform without prior written permission.

---

## 9. Termination

We may suspend or terminate your access to the Platform at any time, for any reason, or no reason, without liability.

All disclaimers, limitations of liability, and indemnification obligations survive termination.

---

## 10. Governing Law

These Terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction determined by the Platform owner, without regard to conflict of law principles.

---

## 11. Contact Information

If you have questions about these Terms, you may contact us at:

**Email:** oleksii.zemliakov@it-knights.club

---

By using PlanProject.ai, you acknowledge that you have read, understood, and agreed to these Terms of Use, including the **complete disclaimer of responsibility and liability**.
`;
